### ISSUE TITLE
No last login info display if "twofactor_gauthenticator" installed

### ISSUE THREAD

**Issue by m0urs** [dsoares/roundcube-lastlogin#17] opened 2016-10-08 11:39 UTC
If I have "twofactor_gauthenticator" installed there is no login info panel displayed if I am logging in if the "twofactor_gauthenticator" plugin asks for a authentication code.

If I tell the "twofactor_gauthenticator" plugin not to ask again for a code on my computer, then for all further logins the login information windows displays correctly.

**Comment by dsoares** [comment] 2016-10-12 16:48
Thank you for filling out this issue. 
I don't know the plugin [twofactor_gauthenticator](https://plugins.roundcube.net/packages/alexandregz/twofactor_gauthenticator), so i have to install  and test it. I'll say something after that.

**Comment by dsoares** [comment] 2016-10-15 12:53
Before installing the plugin twofactor_gauthenticator, i looked into its code. 
I assume you added the plugin lastlogin after the twofactor_gauthenticator in your Roundcube configuration (`$config['plugins']`). 
Could you please try to load lastlogin ***before*** the twofactor_gauthenticator plugin and tell me if it worked?

In `config/config.inc.php`:

    $config['plugins'] = array(
        (...)
        'lastlogin',
        'twofactor_gauthenticator',
        (...)

I'll explain later.

**Comment by m0urs** [comment] 2016-10-15 17:19
I already have that configured that way:

$config['plugins'] = array(
	'archive',
	'google_addressbook',
	'contextmenu',
	'markasjunk2',
	'persistent_login',
	'authres_status',
	'message_highlight',
	'html5_notifier',
	'enigma',
	'dovecot_ident',
	'export_provisioning',
	'removeattachments',
	'rc_smime',
	'automatic_addressbook_ng',
	'managesieve',
	'geolocation',
	'lastlogin',
	'twofactor_gauthenticator',
);

**Comment by j-ed** [comment] 2020-01-10 21:14
I ran into the same problem and first thought both plugins cannot be used at the same time.
I realized that an error was logged when I tried to login:
```
geoip_record_by_name($ip); in ...plugins/geolocation/geolocation.php #119
```
After changing the value of the parameter `$config['geolocation_fetch_method']`from "`system`"
to "`geoplugin`" the error disappeared. I think that the error was caused by a missing local GeoIP
module as described [here](https://www.php.net/manual/en/geoip.setup.php).

**Comment by AlexBeakes** [comment] 2021-03-24 17:16
Have run into the same problem(((

Only with users that have 2FA enabled, that is the only factor that tips off lastlogin.

**Comment by dsoares** [comment] 2021-06-26 12:45
Hi,

The error about function `geoip_record_by_name()` was related to geoip extension (maybe it not installed?). Lastlogin plugin uses `dsoares/geolocation` to get the geolocation IP information. This can be turned off by setting the config option `lastlogin_geolocation` to `false`.

Lastlogin release [1.3.0](https://github.com/dsoares/roundcube-lastlogin/releases/tag/1.3.0) changed the default value of config option `lastlogin_geolocation` to `false`.

I'm going to close the issue because it it not directly related to this project. I must upgrade `dsoares/geolocation` to use the new geoip2 extension when i have the time.

**Closed by dsoares** 2021-06-26 12:45 UTC
